// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBbFFlfaiE0EbY1TfuiHu3EHIrwMpntmg',
    appId: '1:1026520234513:web:0822305b43f87b1b390fb0',
    messagingSenderId: '1026520234513',
    projectId: 'musicalnetworkpasto',
    authDomain: 'musicalnetworkpasto.firebaseapp.com',
    storageBucket: 'musicalnetworkpasto.firebasestorage.app',
    measurementId: 'G-MJ9VMFJ0BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0LQHjBCzwN8PeNhaX_WPLYRDF9OtlzI',
    appId: '1:1026520234513:android:44acb92693da01ac390fb0',
    messagingSenderId: '1026520234513',
    projectId: 'musicalnetworkpasto',
    storageBucket: 'musicalnetworkpasto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD1D79fC1zgB4QG-kKnXV3nskW4o1H-fU',
    appId: '1:1026520234513:ios:102925b41c27759f390fb0',
    messagingSenderId: '1026520234513',
    projectId: 'musicalnetworkpasto',
    storageBucket: 'musicalnetworkpasto.firebasestorage.app',
    iosBundleId: 'com.music.refmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD1D79fC1zgB4QG-kKnXV3nskW4o1H-fU',
    appId: '1:1026520234513:ios:60dc84d44080716b390fb0',
    messagingSenderId: '1026520234513',
    projectId: 'musicalnetworkpasto',
    storageBucket: 'musicalnetworkpasto.firebasestorage.app',
    iosBundleId: 'com.example.refmp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBbFFlfaiE0EbY1TfuiHu3EHIrwMpntmg',
    appId: '1:1026520234513:web:ad4010d2bedc00e0390fb0',
    messagingSenderId: '1026520234513',
    projectId: 'musicalnetworkpasto',
    authDomain: 'musicalnetworkpasto.firebaseapp.com',
    storageBucket: 'musicalnetworkpasto.firebasestorage.app',
    measurementId: 'G-G8P0EL9NZE',
  );
}
